<?php
/** @var $block \Calypso\Testimonial\Block\PostView */
/** @var $post \Calypso\Testimonial\Model\Post */
$post = $block->getPost();
?>
<h1 class="testimonial-post-item-title"><?php echo $post->getTitle() ?></h1>

<div class="testimonial-post-item-content">
    <?php echo $post->getContent(); ?>
</div>

<div class="testimonial-post-item-meta">
    <strong><?php echo __('Created at:') ?></strong> <?php echo $post->getCreationTime() ?>
</div>
